;; -*- mode: eask; lexical-binding: t -*-

(package "blood"
         "0.1.0"
         "An emacs framework")

(website-url "https://github.com/jgrey4296/blood")
(keywords )

(package-file "src/blood.el")
(files "src/blood-*.el"
       "src/blood--*.el"
       "early-init.el"
       '(:exclude "./related/**")
       )

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "30.2")
(depends-on "cl-lib")

(development

 )
